In [4]:
import numpy as np

Найти: А+В, В-А, A*C, A*B*C (руками и кодом)

In [5]:
a = np.array([
    [1, 2, 4],
    [7, 5, -2],
    [-2, 1, 3]
])

b = np.array([
    [-1, 0, 3],
    [2, -6, 1],
    [-7, 1, 5]
])

c = np.array([
    [-2, 3],
    [4, 0],
    [7, -1]
])

In [ ]:
a + b

array([[ 0,  2,  7],
       [ 9, -1, -1],
       [-9,  2,  8]])

In [ ]:
b - a

array([[ -2,  -2,  -1],
       [ -5, -11,   3],
       [ -5,   0,   2]])

In [ ]:
np.dot(a, c)

array([[34, -1],
       [-8, 23],
       [29, -9]])

In [ ]:
d = np.dot(a, b)
d

array([[-25,  -8,  25],
       [ 17, -32,  16],
       [-17,  -3,  10]])

In [ ]:
np.dot(d, c)

array([[ 193, -100],
       [ -50,   35],
       [  92,  -61]])

функция сложения матриц:

In [1]:
def matsum_matrix (matrix1, matrix2):
  result = []
  for row1, row2 in zip(matrix1, matrix2):
    tmp_row = []
    for el1, el2 in zip(row1, row2):
      tmp_el = el1 + el2
      tmp_row.append(tmp_el)
    result.append(tmp_row)
  return result

In [8]:
print(f" python code: {matsum_matrix(a, b)} \n numpy {a+b}")

 python code: [[0, 2, 7], [9, -1, -1], [-9, 2, 8]] 
 numpy [[ 0  2  7]
 [ 9 -1 -1]
 [-9  2  8]]


транспонирование:

In [9]:
def trans_matrix(matrix):
  result = []
  for i in range(len(matrix[0])):
    temp_row = []
    for row in matrix:
      temp_row.append(row[i])
    result.append(temp_row)
  return result

In [10]:
print(f"python code: {trans_matrix(a)} \n numpy: {a.T}")

python code: [[1, 7, -2], [2, 5, 1], [4, -2, 3]] 
 numpy: [[ 1  7 -2]
 [ 2  5  1]
 [ 4 -2  3]]


функция умножения матриц:


In [13]:
def mul_matrix (matrix1, matrix2):
  result = []
  matrix2 = trans_matrix(matrix2)
  for row1 in matrix1:
    temp_row = []
    for row2 in matrix2:
      temp_el = 0
      for el1, el2 in zip(row1, row2):
        temp_el += el1*el2
      temp_row.append(temp_el)
    result.append(temp_row)
  return result

In [14]:
print(f"python code: {mul_matrix(a, b)} \n numpy: {np.dot(a, b)}")

python code: [[-25, -8, 25], [17, -32, 16], [-17, -3, 10]] 
 numpy: [[-25  -8  25]
 [ 17 -32  16]
 [-17  -3  10]]


матричная свёртка:

In [15]:
matrix = np.array([
    [0.5, 0.75, 0.5],
    [0.75, 1, 0.75],
    [0.5, 0.75, 0.5]
])

In [16]:
picture = np.array([
    [12, 14, 41],
    [43, 84, 24],
    [2, 1, 43]
])

In [33]:
def convolution (picture, matrix, div):
  # function requires filter size 3x3

  # new picture creation (border of 0 pixels)
  new_picture = []
  width = len(picture[0]) + 2
  height = len(picture) + 2

  temp_row = []
  for i in range(width):
    temp_row.append(0)
  new_picture.append(temp_row)

  for i in range(height-2):
    temp_row = []
    temp_row.append(0)
    for j in range(width-2):
      temp_row.append(picture[i][j])
    temp_row.append(0)
    new_picture.append(temp_row)

  temp_row = []
  for i in range(width):
    temp_row.append(0)
  new_picture.append(temp_row)

  # filter overlay
  for i in range(height-2):
    for j in range(width-2):
      pixel = np.array([
          [new_picture[i][j], new_picture[i][j+1], new_picture[i][j+2]],
          [new_picture[i+1][j], new_picture[i+1][j+1], new_picture[i+1][j+2]],
          [new_picture[i+2][j], new_picture[i+2][j+1], new_picture[i+2][j+2]]
      ])
      value = 0
      for row1, row2 in zip(pixel, matrix):
        for el1, el2 in zip(row1, row2):
          value += el1 * el2

      picture[i][j] = value * div**(-1)

  return picture


In [34]:
print(convolution(picture, matrix, 6))

[[16 25 18]
 [20 32 26]
 [12 21 17]]
